openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
  description: API for managing User data
servers:
  - url: http://localhost:3000/api

paths:
  /user:
    get:
      summary: Get all User
      tags: [User]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of User
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        'default':
          $ref: '#/components/responses/DefaultResponse'
    post:
      summary: Create a new User
      tags: [User]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreation'
      responses:
        '201':
          description: User created
        'default':
          $ref: '#/components/responses/DefaultResponse'

  /user/{id}:
    get:
      summary: Get User by ID
      tags: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        'default':
          $ref: '#/components/responses/DefaultResponse'

    put:
      summary: Update User
      tags: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreation'
      responses:
        '200':
          description: User updated
        'default':
          $ref: '#/components/responses/DefaultResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    DefaultResponse:
      description: Default error response
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        roleId:
          type: integer
        role:
          type: integer
        orders:
          type: integer
        vehicle:
          type: integer
        rides:
          type: integer
        address:
          type: string
        Location:
          type: integer
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - role
        - orders
        - vehicle
        - rides
        - Location
    UserCreation:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        roleId:
          type: integer
        address:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - role
        - orders
        - vehicle
        - rides
        - Location