openapi: 3.0.3
info:
  title: Location API
  version: 1.0.0
  description: API for managing Location data
servers:
  - url: http://localhost:3000/api

paths:
  /location:
    get:
      summary: Get all Location
      tags: [Location]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of Location
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
        'default':
          $ref: '#/components/responses/DefaultResponse'
    post:
      summary: Create a new Location
      tags: [Location]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationCreation'
      responses:
        '201':
          description: Location created
        'default':
          $ref: '#/components/responses/DefaultResponse'

  /location/{id}:
    get:
      summary: Get Location by ID
      tags: [Location]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A Location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        'default':
          $ref: '#/components/responses/DefaultResponse'

    put:
      summary: Update Location
      tags: [Location]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationCreation'
      responses:
        '200':
          description: Location updated
        'default':
          $ref: '#/components/responses/DefaultResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    DefaultResponse:
      description: Default error response
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
        pincode:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        contact:
          type: integer
        contactId:
          type: integer
        sentOrders:
          type: integer
        receivedOrders:
          type: integer
      required:
        - id
        - contact
        - sentOrders
        - receivedOrders
    LocationCreation:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        pincode:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        contactId:
          type: integer
      required:
        - id
        - contact
        - sentOrders
        - receivedOrders