openapi: 3.0.3
info:
  title: Role API
  version: 1.0.0
  description: API for managing Role data
servers:
  - url: http://localhost:3000/api

paths:
  /role:
    get:
      summary: Get all Role
      tags: [Role]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of Role
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        'default':
          $ref: '#/components/responses/DefaultResponse'
    post:
      summary: Create a new Role
      tags: [Role]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleCreation'
      responses:
        '201':
          description: Role created
        'default':
          $ref: '#/components/responses/DefaultResponse'

  /role/{id}:
    get:
      summary: Get Role by ID
      tags: [Role]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A Role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        'default':
          $ref: '#/components/responses/DefaultResponse'

    put:
      summary: Update Role
      tags: [Role]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleCreation'
      responses:
        '200':
          description: Role updated
        'default':
          $ref: '#/components/responses/DefaultResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    DefaultResponse:
      description: Default error response
  schemas:
    Role:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        users:
          type: integer
        permissions:
          type: integer
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - users
        - permissions
    RoleCreation:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - users
        - permissions