"use client";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {QueryClient, QueryClientProvider} from '@tanstack/react-query';
import {Toaster} from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient();


export default function RootLayout({children}) {
    return (

        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <QueryClientProvider client={queryClient}>
            {children}
            <Toaster
                closeButton
                richColors
                toastOptions={{
                    className: "rounded-md shadow-lg border p-4",
                    style: {
                        fontSize: "14px",
                    },
                }}
                position="top-right"
                duration={3000}
            />
        </QueryClientProvider>
        </body>
        </html>


    );
}
